In [2]:
import numpy as np

# Sudoku 4x4

Un sudoku 4x4 est composé de 4 "blocs". Chaque blocs contient une combinaison de chiffre de 1 à 4 sans répétition. Donc un bloc seul peut contenir $4! = 24$ nombre de façons de placer les 4 nombres. 


Si je commence avec seulement un chiffre seul 1, par exemple, il y à $3! = 6$ facons de placer les autres nombres.


$$\begin{bmatrix}
1 & \_ \\
\_ & \_
\end{bmatrix}$$



In [28]:
from collections import deque

b = np.array([[1,0],[0,0]])

n = 0

for i in range(1,5):
    if i != b[0,0] and i != b[1,1] and i != b[1,0]: 
        b[0,1] = i 
        for j in range(1,5):
            if j != b[0,0] and j != b[1,1] and j != b[0,1]:
                b[1,0] = j
                for k in range(1,5):
                    if k != b[0,0] and k != b[1,0] and k != b[0,1]:
                        b[1,1] = k
                        print(b)
                        b[1,1] = 0
                b[1,0] = 0
        b[0,1] = 0


    

[[1 2]
 [3 4]]
[[1 2]
 [4 3]]
[[1 3]
 [2 4]]
[[1 3]
 [4 2]]
[[1 4]
 [2 3]]
[[1 4]
 [3 2]]
